"""shift_slots

Revision ID: 0aae269b5125
Revises: 29e59a93a93a
Create Date: 2019-09-08 13:54:14.883229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aae269b5125'
down_revision = '29e59a93a93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shift_ibfk_1', 'shift', type_='foreignkey')
    op.create_foreign_key('shift_ibfk_1', 'shift', 'shift_info', ['info_id'], ['shift_info_id'])
    op.drop_constraint('shift_slots_ibfk_3', 'shift_slots', type_='foreignkey')
    op.drop_constraint('shift_slots_ibfk_1', 'shift_slots', type_='foreignkey')
    op.create_foreign_key('shift_slots_ibfk_3', 'shift_slots', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('shift_slots_ibfk_1', 'shift_slots', 'shift', ['shift_id'], ['shift_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shift_slots_ibfk_1', 'shift_slots', type_='foreignkey')
    op.drop_constraint('shift_slots_ibfk_1', 'shift_slots', type_='foreignkey')
    op.create_foreign_key('shift_slots_ibfk_1', 'shift_slots', 'shift', ['shift_id'], ['shift_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('shift_slots_ibfk_3', 'shift_slots', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('shift_ibfk_1', 'shift', type_='foreignkey')
    op.create_foreign_key('shift_ibfk_1', 'shift', 'shift_info', ['info_id'], ['shift_info_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
