"""app_api

Revision ID: 14663f170f29
Revises: 4fa20586eef5
Create Date: 2019-01-31 22:15:53.400285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14663f170f29'
down_revision = '4fa20586eef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('heat_list', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition', 'heat_list')
    # ### end Alembic commands ###
