"""not_selected_last_time

Revision ID: 29e59a93a93a
Revises: f5ef084d728b
Create Date: 2019-07-01 02:02:51.131299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e59a93a93a'
down_revision = 'f5ef084d728b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raffle_configuration', sa.Column('not_selected_last_time_guaranteed_entry', sa.Boolean(), nullable=False))
    op.add_column('raffle_configuration', sa.Column('not_selected_last_time_increased_chance', sa.Boolean(), nullable=False))
    op.add_column('system_configuration', sa.Column('additional_teamcaptain_large_teams', sa.Boolean(), nullable=False))
    op.add_column('system_configuration', sa.Column('additional_teamcaptain_large_teams_cutoff', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_configuration', 'additional_teamcaptain_large_teams_cutoff')
    op.drop_column('system_configuration', 'additional_teamcaptain_large_teams')
    op.drop_column('raffle_configuration', 'not_selected_last_time_increased_chance')
    op.drop_column('raffle_configuration', 'not_selected_last_time_guaranteed_entry')
    # ### end Alembic commands ###
