"""initial

Revision ID: 3c9e80ff9c9b
Revises: 
Create Date: 2018-06-08 08:50:18.763296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9e80ff9c9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contestants',
    sa.Column('contestant_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('prefixes', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('contestant_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('merchandise',
    sa.Column('merchandise_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=False),
    sa.Column('product_description', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('merchandise_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tournament_state',
    sa.Column('lock', sa.Integer(), nullable=False),
    sa.Column('main_raffle_taken_place', sa.Boolean(), nullable=False),
    sa.Column('main_raffle_result_visible', sa.Boolean(), nullable=False),
    sa.Column('numbers_rearranged', sa.Boolean(), nullable=False),
    sa.Column('raffle_completed_message_sent', sa.Boolean(), nullable=False),
    sa.Column('tournament_config', sa.String(length=2048), nullable=False),
    sa.Column('raffle_config', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('lock')
    )
    op.create_table('additional_info',
    sa.Column('contestant_id', sa.Integer(), nullable=False),
    sa.Column('sleeping_arrangements', sa.Boolean(), nullable=False),
    sa.Column('t_shirt', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.contestant_id'], ),
    sa.PrimaryKeyConstraint('contestant_id')
    )
    op.create_table('contestant_info',
    sa.Column('contestant_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('team_captain', sa.Boolean(), nullable=False),
    sa.Column('student', sa.Boolean(), nullable=False),
    sa.Column('first_time', sa.Boolean(), nullable=False),
    sa.Column('Diet/Allergies', sa.String(length=512), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.contestant_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('contestant_id')
    )
    op.create_index(op.f('ix_contestant_info_first_time'), 'contestant_info', ['first_time'], unique=False)
    op.create_index(op.f('ix_contestant_info_student'), 'contestant_info', ['student'], unique=False)
    op.create_table('dancing_info',
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('contestant_id', sa.Integer(), nullable=True),
    sa.Column('competition', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('blind_date', sa.Boolean(), nullable=False),
    sa.Column('partner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.contestant_id'], ),
    sa.PrimaryKeyConstraint('contest_id'),
    sa.UniqueConstraint('contestant_id', 'competition', 'level')
    )
    op.create_table('merchandise_info',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('contestant_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.contestant_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('name_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contestant_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('prefixes', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.contestant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=128), nullable=False),
    sa.Column('competition', sa.String(length=128), nullable=False),
    sa.Column('dancer_id', sa.Integer(), nullable=True),
    sa.Column('other_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dancer_id'], ['contestants.contestant_id'], ),
    sa.ForeignKeyConstraint(['other_id'], ['contestants.contestant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_request_timestamp'), 'partner_request', ['timestamp'], unique=False)
    op.create_table('status_info',
    sa.Column('contestant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('payment_required', sa.Boolean(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('raffle_status', sa.String(length=16), nullable=True),
    sa.Column('guaranteed_entry', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.contestant_id'], ),
    sa.PrimaryKeyConstraint('contestant_id')
    )
    op.create_index(op.f('ix_status_info_paid'), 'status_info', ['paid'], unique=False)
    op.create_index(op.f('ix_status_info_payment_required'), 'status_info', ['payment_required'], unique=False)
    op.create_index(op.f('ix_status_info_raffle_status'), 'status_info', ['raffle_status'], unique=False)
    op.create_index(op.f('ix_status_info_status'), 'status_info', ['status'], unique=False)
    op.create_table('team_finances',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('send_new_messages_email', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_access'), 'users', ['access'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_password_hash'), 'users', ['password_hash'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('volunteer_info',
    sa.Column('contestant_id', sa.Integer(), nullable=False),
    sa.Column('volunteer', sa.String(length=16), nullable=False),
    sa.Column('first_aid', sa.String(length=16), nullable=False),
    sa.Column('jury_ballroom', sa.String(length=16), nullable=False),
    sa.Column('jury_latin', sa.String(length=16), nullable=False),
    sa.Column('license_jury_ballroom', sa.String(length=16), nullable=False),
    sa.Column('license_jury_latin', sa.String(length=16), nullable=False),
    sa.Column('jury_salsa', sa.String(length=16), nullable=False),
    sa.Column('jury_polka', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.contestant_id'], ),
    sa.PrimaryKeyConstraint('contestant_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('unread', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('destination', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_archived'), 'notifications', ['archived'], unique=False)
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'], unique=False)
    op.create_index(op.f('ix_notifications_unread'), 'notifications', ['unread'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_unread'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_archived'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('volunteer_info')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password_hash'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_access'), table_name='users')
    op.drop_table('users')
    op.drop_table('team_finances')
    op.drop_index(op.f('ix_status_info_status'), table_name='status_info')
    op.drop_index(op.f('ix_status_info_raffle_status'), table_name='status_info')
    op.drop_index(op.f('ix_status_info_payment_required'), table_name='status_info')
    op.drop_index(op.f('ix_status_info_paid'), table_name='status_info')
    op.drop_table('status_info')
    op.drop_index(op.f('ix_partner_request_timestamp'), table_name='partner_request')
    op.drop_table('partner_request')
    op.drop_table('name_change_requests')
    op.drop_table('merchandise_info')
    op.drop_table('dancing_info')
    op.drop_index(op.f('ix_contestant_info_student'), table_name='contestant_info')
    op.drop_index(op.f('ix_contestant_info_first_time'), table_name='contestant_info')
    op.drop_table('contestant_info')
    op.drop_table('additional_info')
    op.drop_table('tournament_state')
    op.drop_table('teams')
    op.drop_table('merchandise')
    op.drop_table('contestants')
    # ### end Alembic commands ###
