"""auth_code

Revision ID: 57b7d8b0113c
Revises: 5db5366a3f7e
Create Date: 2019-11-09 13:57:25.606454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b7d8b0113c'
down_revision = '5db5366a3f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_code', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_code')
    # ### end Alembic commands ###
