"""finalize_merchandise

Revision ID: 7dfe1ba3b364
Revises: c06fd73d0f7a
Create Date: 2018-11-20 13:28:14.120089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dfe1ba3b364'
down_revision = 'c06fd73d0f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contestant_info', 'student',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=128),
               nullable=False)
    op.add_column('tournament_state', sa.Column('merchandise_finalized', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_state', 'merchandise_finalized')
    op.alter_column('contestant_info', 'student',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=128),
               nullable=True)
    # ### end Alembic commands ###
