"""bus

Revision ID: 9d979efd3438
Revises: 3c9e80ff9c9b
Create Date: 2018-06-09 02:43:35.728134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d979efd3438'
down_revision = '3c9e80ff9c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_info', sa.Column('bus_to_brno', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('additional_info', 'bus_to_brno')
    # ### end Alembic commands ###
