"""send_messages_toggle

Revision ID: 9eae7b74051a
Revises: ba6b887c9414
Create Date: 2018-06-08 01:09:56.737250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eae7b74051a'
down_revision = 'ba6b887c9414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_new_messages_email', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('send_new_messages_email')

    # ### end Alembic commands ###
