"""merchandise

Revision ID: ba6b887c9414
Revises: ab3e0b0cf0dd
Create Date: 2018-06-06 21:05:34.689175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6b887c9414'
down_revision = 'ab3e0b0cf0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchandise',
    sa.Column('merchandise_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=False),
    sa.Column('product_description', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('merchandise_id')
    )
    op.create_table('merchandise_info',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('contestant_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.contestant_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.add_column('tournament_state', sa.Column('raffle_completed_message_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_state', 'raffle_completed_message_sent')
    op.drop_table('merchandise_info')
    op.drop_table('merchandise')
    # ### end Alembic commands ###
