"""jury_level

Revision ID: cd2a7282cca7
Revises: d9f23d164a4e
Create Date: 2018-06-26 10:57:24.747372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2a7282cca7'
down_revision = 'd9f23d164a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_info', sa.Column('level_ballroom', sa.String(length=16), server_default='Below D', nullable=False))
    op.add_column('volunteer_info', sa.Column('level_latin', sa.String(length=16), server_default='Below D', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_info', 'level_latin')
    op.drop_column('volunteer_info', 'level_ballroom')
    # ### end Alembic commands ###
