"""diet_notes

Revision ID: d0b0160636dc
Revises: 7dfe1ba3b364
Create Date: 2018-12-03 14:29:41.444388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b0160636dc'
down_revision = '7dfe1ba3b364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestant_info', sa.Column('Diet/Allergies Notes', sa.String(length=512), nullable=True))
    op.add_column('super_volunteer', sa.Column('Diet/Allergies Notes', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('super_volunteer', 'Diet/Allergies Notes')
    op.drop_column('contestant_info', 'Diet/Allergies Notes')
    # ### end Alembic commands ###
