"""empty message

Revision ID: d5592bf71272
Revises: cd2a7282cca7
Create Date: 2018-09-29 14:54:52.542147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5592bf71272'
down_revision = 'cd2a7282cca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_info', sa.Column('checked_in', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status_info', 'checked_in')
    # ### end Alembic commands ###
