"""salsa_polka_couples

Revision ID: d9f23d164a4e
Revises: 9d979efd3438
Create Date: 2018-06-13 16:09:20.497186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f23d164a4e'
down_revision = '9d979efd3438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polka_partners',
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('follow_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('couple_id')
    )
    op.create_table('salsa_partners',
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('follow_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('couple_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salsa_partners')
    op.drop_table('polka_partners')
    # ### end Alembic commands ###
