"""ask_drinks

Revision ID: faffbc0bc3ca
Revises: 09f03a08fa5a
Create Date: 2019-05-29 12:57:02.319772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faffbc0bc3ca'
down_revision = '09f03a08fa5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestant_info', sa.Column('adult', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_contestant_info_adult'), 'contestant_info', ['adult'], unique=False)
    op.add_column('system_configuration', sa.Column('ask_adult', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_configuration', 'ask_adult')
    op.drop_index(op.f('ix_contestant_info_adult'), table_name='contestant_info')
    op.drop_column('contestant_info', 'adult')
    # ### end Alembic commands ###
