#!/bin/bash


clear
echo "Settings:"
echo "========="
echo "xTDS domain:"
echo $XTDS_DOMAIN
echo "NTDS domain:"
echo $NTDS_DOMAIN
echo "Install base dependencies and SSL certificate? (y/n)"
read continue
if [[ $continue = "y" ]]
then
echo "Starting base installation"

echo "Updating system==============================="
cd
sudo apt -y update
sudo apt -y upgrade
echo "System updated================================"


echo "Installing install_base dependencies=================="
sudo apt -y install supervisor python3 python3-venv python3-dev mysql-server supervisor nginx git npm
echo "Base dependencies installed==================="


echo "Installing SSL certificate===================="
sudo apt install -y software-properties-common
sudo add-apt-repository -y universe
sudo add-apt-repository -y ppa:certbot/certbot
sudo apt install -y certbot python-certbot-nginx
sudo certbot certonly --nginx -d $XTDS_DOMAIN -d mail.$XTDS_DOMAIN -d test.$XTDS_DOMAIN -d dev.$XTDS_DOMAIN
sudo certbot certonly --nginx -d $NTDS_DOMAIN
echo "Installing SSL certificate complete==========="


echo "Configuring firewall=========================="
sudo apt -y install ufw
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw --force enable
echo "Configuring firewall complete================="


echo "Installing local mail server=================="
sudo bash -c 'cat > /etc/supervisor/conf.d/xtds_local_mail.conf' << EOL
[program:xtds_local_mail]
command=python -m smtpd -n -c DebuggingServer localhost:8025
user=$USER
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
EOL
sudo supervisorctl reload
echo "Installed local mail server==================="



else
echo "Cancelling installation."
fi
cd
